# Change these first
owner: coincord # Your GitHub organization or username, where this repository lives
repo: coincord-status # The name of this repository

sites:
  - name: Coincord Website
    url: https://www.coincord.co
    icon: https://coincord.co/images/favicon.ico
  - name: Coincord Documentation
    url: https://developers.coincord.co
    icon: https://coincord.co/images/favicon.ico
  - name: Coincord Mobile API
    url: $SECRET_MOBILE
    method: POST
    icon: https://coincord.co/images/favicon.ico
    headers:
      - "Content-Type: application/json"
    body: "{\"query\":\"query{load_user(username:\\\"tbekz\\\"){username}}\"}"
    
assignees:
  - cuddimatic
  - Mozartted

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.coincord.co
  # baseUrl: /coincord-status
  logoUrl: https://coincord.co/svgs/main_logo.svg
  name: Status
  introTitle: "**Coincord** | The future of DeFi Finance"
  introMessage: Coincord is a blockchain-focused fintech product that aims to make the average crypto token Spendable
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
